application:
  title: Api USer
  version: 0.0.1
server:
  port: 8089
spring:
  application:
    name: API USER
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  cache:
    type: redis
rabbitmq:
  exchange:
    email:
      direct: api.user.direct
    user:
      fanout: api.user.fanout
  routingkey:
    email: email.valid.fail.routingkey
    user: new.users.routingkey
  queue:
    email:
      valid:
        fail: email.valid.fail
    user:
      new: new.users
logging:
  level:
    root: INFO
api:
  email:
    url: ${API_EMAIL_URL}
resilience4j:
  circuitbreaker:
    instances:
      apiEmail:
        registerHealthIndicator: true
        slidingWindowSize: 4
        minimumNumberOfCalls: 2